esphome:
  name: home-assistant-voice-pe
  friendly_name: Home Assistant Voice Preview Edition

packages:
  home-assistant-voice: github://esphome/home-assistant-voice-pe/home-assistant-voice.factory.yaml@25.1.0

dashboard_import:
  import_full_config: true
